ALTER TABLE municipio
DROP FOREIGN KEY fk_MUNICIPIO_PERSONA;

ALTER TABLE municipio
ADD CONSTRAINT fk_MUNICIPIO_PERSONA
FOREIGN KEY (PERSONA_id_persona)
REFERENCES persona(id_persona)
ON DELETE SET NULL
ON UPDATE CASCADE;

