-- SE MODIFICAN LOS CONSTRAINTS DE LAS FKS
-- PARA QUE UNA VEZ SE BORRE UNA ENTIDAD A LA QUE SE HACE REFERENCIA
-- SE DEJE CAMPO NULO O NO SE PUEDA. TAMBIEN SE CONFIGURA EN CASO DE 
-- QUE SE ACTUALICE


-- PERSONA
ALTER TABLE persona
DROP FOREIGN KEY fk_PERSONA_PERSONA1;

ALTER TABLE persona
ADD CONSTRAINT fk_PERSONA_PERSONA1
FOREIGN KEY (PERSONA_id_persona)
REFERENCES persona(id_persona)
ON DELETE SET NULL
ON UPDATE CASCADE;

ALTER TABLE persona
DROP FOREIGN KEY fk_PERSONA_VIVIENDA1;

ALTER TABLE persona
ADD CONSTRAINT fk_PERSONA_VIVIENDA1
FOREIGN KEY (VIVIENDA_id_vivienda)
REFERENCES vivienda(id_vivienda)
ON DELETE SET NULL
ON UPDATE CASCADE;

-- MUNICIPIO
ALTER TABLE municipio
DROP FOREIGN KEY fk_MUNICIPIO_PERSONA;

ALTER TABLE municipio
ADD CONSTRAINT fk_MUNICIPIO_PERSONA
FOREIGN KEY (PERSONA_id_persona)
REFERENCES persona(id_persona)
ON DELETE SET NULL
ON UPDATE CASCADE;

ALTER TABLE municipio
DROP FOREIGN KEY fk_MUNICIPIO_DEPARTAMENTO1;

ALTER TABLE municipio
ADD CONSTRAINT fk_MUNICIPIO_DEPARTAMENTO1
FOREIGN KEY (DEPARTAMENTO_id_departamento)
REFERENCES DEPARTAMENTO(id_departamento)
ON DELETE NO ACTION
ON UPDATE CASCADE;

-- PERSONA_has_VIVIENDA
ALTER TABLE persona_has_vivienda
DROP FOREIGN KEY fk_PERSONA_has_VIVIENDA_PERSONA1;

ALTER TABLE persona_has_vivienda
ADD CONSTRAINT fk_PERSONA_has_VIVIENDA_PERSONA1
FOREIGN KEY (PERSONA_id_persona)
REFERENCES persona(id_persona)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE persona_has_vivienda
DROP FOREIGN KEY fk_PERSONA_has_VIVIENDA_VIVIENDA1;

ALTER TABLE persona_has_vivienda
ADD CONSTRAINT fk_PERSONA_has_VIVIENDA_VIVIENDA1
FOREIGN KEY (VIVIENDA_id_vivienda)
REFERENCES vivienda(id_vivienda)
ON DELETE CASCADE
ON UPDATE CASCADE;

-- responsable
ALTER TABLE responsable
DROP FOREIGN KEY fk_PROYECTO_has_PERSONA_PERSONA1,
DROP FOREIGN KEY fk_PROYECTO_has_PERSONA_PROYECTO1;

ALTER TABLE responsable
ADD CONSTRAINT fk_PROYECTO_has_PERSONA_PERSONA1
FOREIGN KEY (PERSONA_id_persona)
REFERENCES persona(id_persona)
ON UPDATE CASCADE
ON DELETE CASCADE,
ADD CONSTRAINT fk_PROYECTO_has_PERSONA_PROYECTO1
FOREIGN KEY (PROYECTO_id_proyecto)
REFERENCES proyecto(id_proyecto)
ON UPDATE CASCADE
ON DELETE CASCADE;

-- Proyecto
ALTER TABLE proyecto
DROP FOREIGN KEY fk_PROYECTO_MUNICIPIO1;

ALTER TABLE proyecto
ADD CONSTRAINT fk_PROYECTO_MUNICIPIO1
FOREIGN KEY (MUNICIPIO_id_municipio)
REFERENCES municipio(id_municipio)
ON UPDATE CASCADE
ON DELETE CASCADE;

-- Vivienda
ALTER TABLE VIVIENDA
DROP FOREIGN KEY fk_VIVIENDA_MUNICIPIO1;

ALTER TABLE VIVIENDA
ADD CONSTRAINT fk_VIVIENDA_MUNICIPIO1
FOREIGN KEY (MUNICIPIO_id_municipio)
REFERENCES MUNICIPIO(id_municipio)
ON DELETE CASCADE
ON UPDATE CASCADE;

-- EVENTO
ALTER TABLE evento
DROP FOREIGN KEY fk_EVENTO_MUNICIPIO1;

ALTER TABLE evento
ADD CONSTRAINT fk_EVENTO_MUNICIPIO1
FOREIGN KEY (MUNICIPIO_id_municipio)
REFERENCES municipio(id_municipio)
ON UPDATE CASCADE
ON DELETE CASCADE;