-- Modificar columnas de clave foránea para permitir valores NULL
ALTER TABLE PERSONA MODIFY COLUMN PERSONA_id_persona INT NULL,
MODIFY COLUMN VIVIENDA_id_vivienda INT NULL;

ALTER TABLE MUNICIPIO MODIFY COLUMN PERSONA_id_persona INT NULL,
MODIFY COLUMN DEPARTAMENTO_id_departamento INT NULL;

ALTER TABLE PROYECTO MODIFY COLUMN MUNICIPIO_id_municipio INT NULL;

ALTER TABLE VIVIENDA MODIFY COLUMN MUNICIPIO_id_municipio INT NULL;

ALTER TABLE EVENTO MODIFY COLUMN MUNICIPIO_id_municipio INT NULL;

-- SE MODIFICAN LOS CONSTRAINTS DE LAS FKS
-- PARA QUE UNA VEZ SE BORRE UNA ENTIDAD A LA QUE SE HACE REFERENCIA
-- SE DEJE CAMPO NULO O NO SE PUEDA. TAMBIEN SE CONFIGURA EN CASO DE 
-- QUE SE ACTUALICE
-- PERSONA
ALTER TABLE PERSONA
DROP FOREIGN KEY fk_PERSONA_PERSONA1;

ALTER TABLE PERSONA ADD CONSTRAINT fk_PERSONA_PERSONA1 FOREIGN KEY (PERSONA_id_persona) REFERENCES PERSONA (id_persona) ON DELETE SET NULL ON UPDATE NO ACTION;

ALTER TABLE PERSONA
DROP FOREIGN KEY fk_PERSONA_VIVIENDA1;

ALTER TABLE PERSONA ADD CONSTRAINT fk_PERSONA_VIVIENDA1 FOREIGN KEY (VIVIENDA_id_vivienda) REFERENCES VIVIENDA (id_vivienda) ON DELETE SET NULL ON UPDATE CASCADE;

-- MUNICIPIO
ALTER TABLE MUNICIPIO
DROP FOREIGN KEY fk_MUNICIPIO_PERSONA;

ALTER TABLE MUNICIPIO ADD CONSTRAINT fk_MUNICIPIO_PERSONA FOREIGN KEY (PERSONA_id_persona) REFERENCES PERSONA (id_persona) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE MUNICIPIO
DROP FOREIGN KEY fk_MUNICIPIO_DEPARTAMENTO1;

ALTER TABLE MUNICIPIO ADD CONSTRAINT fk_MUNICIPIO_DEPARTAMENTO1 FOREIGN KEY (DEPARTAMENTO_id_departamento) REFERENCES DEPARTAMENTO (id_departamento) ON DELETE CASCADE ON UPDATE CASCADE;

-- PERSONA_has_VIVIENDA
ALTER TABLE PERSONA_has_VIVIENDA
DROP FOREIGN KEY fk_PERSONA_has_VIVIENDA_PERSONA1;

ALTER TABLE PERSONA_has_VIVIENDA ADD CONSTRAINT fk_PERSONA_has_VIVIENDA_PERSONA1 FOREIGN KEY (PERSONA_id_persona) REFERENCES PERSONA (id_persona) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE PERSONA_has_VIVIENDA
DROP FOREIGN KEY fk_PERSONA_has_VIVIENDA_VIVIENDA1;

ALTER TABLE PERSONA_has_VIVIENDA ADD CONSTRAINT fk_PERSONA_has_VIVIENDA_VIVIENDA1 FOREIGN KEY (VIVIENDA_id_vivienda) REFERENCES VIVIENDA (id_vivienda) ON DELETE CASCADE ON UPDATE CASCADE;

-- responsable
ALTER TABLE RESPONSABLE
DROP FOREIGN KEY fk_PROYECTO_has_PERSONA_PERSONA1,
DROP FOREIGN KEY fk_PROYECTO_has_PERSONA_PROYECTO1;

ALTER TABLE RESPONSABLE ADD CONSTRAINT fk_PROYECTO_has_PERSONA_PERSONA1 FOREIGN KEY (PERSONA_id_persona) REFERENCES PERSONA (id_persona) ON UPDATE CASCADE ON DELETE CASCADE,
ADD CONSTRAINT fk_PROYECTO_has_PERSONA_PROYECTO1 FOREIGN KEY (PROYECTO_id_proyecto) REFERENCES PROYECTO (id_proyecto) ON UPDATE CASCADE ON DELETE CASCADE;

-- Proyecto
ALTER TABLE PROYECTO
DROP FOREIGN KEY fk_PROYECTO_MUNICIPIO1;

ALTER TABLE PROYECTO ADD CONSTRAINT fk_PROYECTO_MUNICIPIO1 FOREIGN KEY (MUNICIPIO_id_municipio) REFERENCES MUNICIPIO (id_municipio) ON UPDATE CASCADE ON DELETE CASCADE;

-- Vivienda
ALTER TABLE VIVIENDA
DROP FOREIGN KEY fk_VIVIENDA_MUNICIPIO1;

ALTER TABLE VIVIENDA ADD CONSTRAINT fk_VIVIENDA_MUNICIPIO1 FOREIGN KEY (MUNICIPIO_id_municipio) REFERENCES MUNICIPIO (id_municipio) ON DELETE CASCADE ON UPDATE CASCADE;

-- EVENTO
ALTER TABLE EVENTO
DROP FOREIGN KEY fk_EVENTO_MUNICIPIO1;

ALTER TABLE EVENTO ADD CONSTRAINT fk_EVENTO_MUNICIPIO1 FOREIGN KEY (MUNICIPIO_id_municipio) REFERENCES MUNICIPIO (id_municipio) ON UPDATE CASCADE ON DELETE CASCADE;